---
- hosts: all
  tags: always
  become: true
  tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: false
      when: ansible_distribution == "Archlinux"

    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: false
      when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: localhost
  roles:
    - role: base
    - role: zsh
    - role: tmux
    - role: fonts
    - role: git
    - role: ssh
    - role: rust
    - role: bat
    - role: vim
    - role: golang

- hosts: all
  become: true
  tasks:
    - name: cleanup package cache (debian and ubuntu)
      tags: always
      apt:
        autoclean: true
      changed_when: false
      when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

    - name: autoremove orphan packages (debian and ubuntu)
      tags: always
      apt:
        autoremove: true
        purge: true
      when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
