---
- name: git | copy gitalias
  tags: dotfiles,git
  copy:
    src: "{{ item.src }}"
    dest: "{{ home_dir }}/{{ item.dest }}"
    mode: 0600
  with_items:
    - { src: 'gitalias', dest: '.gitalias' }

- name: git | Create gitconfig from template
  tags: dotfiles,git
  template:
    src: git.cfg.j2
    dest: ~/.gitconfig
    mode: 0600