---
- name: repositories | add ignored packages for archlinux hosts
  tags: packages,repositories
  become: true
  lineinfile:
      dest: /etc/pacman.conf
      regexp: "^#?IgnorePkg"
      line: "IgnorePkg   = ansible linux linux-headers linux-lts linux-lts-headers"
  when: ansible_distribution == "Archlinux"

- name: repositories | install package management tools (debian-based)
  tags: packages,system,settings
  become: true
  package:
      state: present
      name:
          - aptitude
          - software-properties-common
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
