- name: ansible setup | create ansible log file
  tags: ansible,ansible-setup
  become: true
  file:
    path: /var/log/ansible.log
    owner: "{{ user }}"
    mode: 0664
    state: touch
  changed_when: False


- name: ansible setup | add logrotate config for ansible log file
  become: true
  tags: ansible-setup
  copy:
    src: logrotate
    dest: /etc/logrotate.d/ansible
    owner: root
    group: root
    mode: 0644

- name: ensure ansible is the latest version
  tags: base,ansible
  become: true
  package:
    name: ansible
    state: present

- name: ansible setup | generate provision script from template
  tags: ansible,ansible-setup,scripts
  become: true
  template:
    src: cli_ansible_pull.sh.j2
    dest: /usr/local/bin/cli_ansible_pull.sh
    owner: root
    group: root
    mode: 0755