---
- name: cron | install cron package
  tags: packages,cron
  become: true
  package:
    name:
      - "{{ cron_package }}"
    state: present

- name: cron | start and enable cronie daemon
  tags: cron
  service:
    name: cronie
    state: started
    enabled: true
  when: ansible_distribution == "Archlinux"
