---
- name: Install neovim
  tags: nvim,vim
  package:
    state: present
    name:
      - neovim

- name: Create config directories
  tags: dotfiles,nvim,vim
  file:
    dest: "{{ home_dir }}/{{ item.dir }}"
    state: directory
    mode: 0700
  with_items:
    - { dir: '.config/nvim' }

- name: Copy config nvim
  tags: dotfiles,nvim,vim
  copy:
    src: "{{ item.src }}"
    dest: "{{ home_dir }}/.config/nvim/{{ item.dest }}"
    mode: 0600
  with_items:
    - { src: 'init.vim', dest: 'init.vim' }