---
- name: Install fontconfig
  become: "{{ ansible_os_family == 'Debian' }}"
  package:
    state: present
    name: "{{ item }}"
  with_items:
    - fontconfig
  tags:
    - packages
    - fonts

- name: Download powerline-fonts repository from github
  git:
    repo: 'https://github.com/powerline/fonts.git'
    dest: /tmp/powerline-fonts
    version: 'HEAD'
  tags:
    - fonts

- name: Ensure a local fonts directory exists
  tags: fonts
  file:
    dest: "{{ user_home }}/.local/share/fonts"
    state: directory
    owner: "{{ user }}"
    mode: 0700

- name: Create font directories
  tags: fonts
  file:
    dest: "{{ user_home }}/.local/share/fonts/{{ item.font_family }}"
    state: directory
    owner: "{{ user }}"
    mode: 0700
  with_items: "{{ fonts }}"

- name: Copy font files
  tags: fonts
  copy:
    src: "{{ item.0.src_dir }}/{{ item.0.font_family }}/{{ item.1 }}"
    dest: "{{ user_home }}/.local/share/fonts/{{ item.0.font_family }}/{{ item.1 }}"
    mode: 0600
  with_subelements:
    - "{{ fonts }}"
    - font_files

- name: Reset font cache
  command: fc-cache -v {{ user_home }}/.local/share/fonts
  register: stdout
  changed_when: "'new cache contents' in stdout.stdout"
  tags:
    - fonts
