---
- name: Install fontconfig
  become: "{{ ansible_os_family == 'Debian' }}"
  package:
    state: present
    name: "{{ item }}"
  with_items:
    - fontconfig
  tags:
    - packages
    - fonts

- name: Ensure a local fonts directory exists
  tags: fonts
  file:
    dest: "{{ user_home }}/.local/share/{{ item }}"
    state: directory
    owner: "{{ user }}"
    mode: 0700
  with_items:
    - 'fonts'
    - 'fonts/Hack'

- name: Download patched Hack font
  tags: fonts
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
    dest: "{{ user_home }}/.local/share/fonts/Hack/"
    remote_src: true

- name: Reset font cache
  command: fc-cache -v {{ user_home }}/.local/share/fonts
  register: stdout
  changed_when: "'new cache contents' in stdout.stdout"
  tags:
    - fonts
